version: '3'
services:

  db:
    image: mariadb
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/my.cnf
      - ./backups/sql:/opt/backups
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--innodb-read-only-compressed=OFF"
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=Europe/Paris

  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data

  app:
    build: ./app
    working_dir: /var/www/html
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - ./app/moodle_data:/var/moodledata
      - content:/var/www/html
      - ./app/config.php:/var/www/html/config.php
    ports:
      - 9000:9000
  nginx:
    build: ./nginx/prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/prod/moodle.conf:/etc/nginx/nginx.conf:ro
      - content:/var/www/html:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: always
    depends_on:
      - db
      - app

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  db_data:
    driver: local
  redis_data:
  content:
